### ISSUE TITLE
bulk download

### ISSUE THREAD

**Issue by chreman** [ContentMine/canary#3]
Having a bulk download button would be great, to locally recreate what would've been the result if I ran everything on the VM - essentially only copying the workspace. A tar or zip wouldn't be too big?

**Comment by markmacgillivray** [comment]
It is currently possible to get everything that the commands produce from the store directory of your workspace - there is no simple button that delivers it all, but you could use a recursive wget command to get everything from it for the time being. This issue will be kept open as a good addition later, but not current priority I think.
