### ISSUE TITLE
Explore producing an updated IUCn

### ISSUE THREAD

**Issue by markmacgillivray** [ContentMine/canary#8]
Can we, given the current IUCn list, and an update of the species in it on our demo, regularly produce an updated list where we move species based on what we learn about them? Perhaps we can identify certain statements that we can take as meaning a species is no longer endangered? Or has become endangered? Perhaps @Blahah or @rossmounce can provide input here.

**Comment by petermr** [comment]
We could combine regex and species in same sentence. Regex would be words such as endangered vulnerable most concern etc

**Comment by blahah** [comment]
I like the basic idea. IUCN classifications are quite involved and usually require a panel of experts to set or change the status. We could do something like, given the existing status and the data we have mined, indicate whether the species seems to be improving, declining, or being maintained relative to when it was last assessed? A classification like that avoids treading on the toes of the existing experts, but provides value beyond the simple facts.

**Comment by markmacgillivray** [comment]
This sounds good. I think we only need the species plugin, not regex - once
we have the species I can search for the ones with interesting words in
their pre and post strings. From this we could provide a heat map of
research activity around the species we can match on the iucn red list.
Then consider what further statements we can say about them, in support of
the experts.
